app/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls")),
    path('requirements/',include("requirements.urls")),
    path('inquiry/', include('inquiry.urls')),
    path('portral/',include("portral.urls")),
    path("", lambda request: redirect("accounts:login")),
    path('answers/', include('answers.urls')),
]

app/requirements/models.py
from django.db import models
import uuid
from pathlib import Path
from accounts.models import Users

class Requirements(models.Model):
    user_id=models.ForeignKey(Users,
                           on_delete=models.CASCADE,
                           db_column='user_id',
                           to_field='id',verbose_name='ユーザーID')
    title=models.CharField(max_length=255,null=False,verbose_name='タイトル')
    content=models.TextField(null=False,verbose_name='内容')
    difficulty = models.CharField(max_length=10, choices=[
    ('low', '初級'),
    ('mid', '中級'),
    ('high', '上級'),
    ], default='mid',verbose_name='難易度')
    participants=models.IntegerField(default=0,verbose_name='参加人数')
    #techは削除
    team=models.CharField(null=False,max_length=255,verbose_name='チーム名')
    is_public=models.BooleanField(default=False,verbose_name='公表、非公表')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

class Articles(models.Model):
    requirement_id=models.ForeignKey(Requirements,
                                     on_delete=models.CASCADE,
                                     db_column='requirements_id',
                                     to_field='id')
    category_choices=[
        ('frontend','フロントエンド'),
        ('backend','バックエンド'),
        ('infra','インフラ')
    ]
    categories=models.CharField(max_length=20,
                                choices=category_choices,
                                null=False,
                                verbose_name='カテゴリー')
    title=models.CharField(max_length=255,null=False,verbose_name='タイトル')
    url=models.TextField(null=False,verbose_name='url')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

class tech_stacks(models.Model):
    title=models.CharField(max_length=63,null=False,verbose_name='技術名')
    img_url=models.URLField(null=False,verbose_name='画像のurl')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

class requirements_tech_stacks(models.Model):
    requirement_id=models.ForeignKey(Requirements,
                                     on_delete=models.CASCADE,
                                     db_column='requirements_id',
                                     to_field='id')
    tech_stack_id=models.ForeignKey(tech_stacks,
                                     on_delete=models.CASCADE,
                                     db_column='tech_stack_id',
                                     to_field='id')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

app/templates/components/header.html
{% load static %}
<header class="header">
  <div class="header--wrap">
    <div class="header--right">
      <a href="/portral/requirements"><img src="{% static 'img/logo_icon.png' %}" class="header--right__main-logo" /></a>
      <nav class="header--right__nav">
        <ul class="header--right__nav-ul">
          <li>
            <a href="/portral/requirements">
              <div>要件一覧</div>
              <div id="portral" class="header--right__nav-buttom"></div>
            </a>
          </li>
          <li>
            <a href="/inquiry">
              <div>FAQ</div>
              <div id="inquiry" class="header--right__nav-buttom"></div>
            </a>
          </li>
          <li>
            <a href="#">
              <div>過去履歴</div>
              <div class="header--right__nav-buttom"></div>
            </a>
          </li>
        </ul>
      </nav>
    </div>
    <a href="/accounts">
      <div class="header--left">
        <img src="{% static 'img/user.png' %}" class="user-icon" />
      </div>
    </a>
  </div>
</header>

app/templates/components/requirements_sheet.html
<div class="requirements">
  <div class="requirements--titles">
    <h2 class="requirements--titles__title">{{req_detail.title}}</h2>
    <div class="requirements--titles__contents">
      <div class="requirements--titles__contents-title">応募数</div>
      <div class="requirements--titles__contents-border"></div>
      <div class="requirements--titles__contents-main">{{req_detail.participants}}人</div>
    </div>
  </div>
  <div class="requirements--contents">
    <div class="requirements--contents__requirement">
      <h3 class="requirements--contents__title">要件</h3>
      <p class="requirements--contents__content">{{req_detail.content}}</p>
    </div>
    <div>
      <h3 class="requirements--contents__title">使用技術</h3>
      <div class="requirements--contents__content">
        <div class="requirements--contents__content-tech">
          {% for tech_stack in req_detail.requirements_tech_stacks_set.all %}
          <div class="requirements--contents__content-tech-icon">
            <img
              src="{{ tech_stack.tech_stack_id.img_url }}"
              alt="{{ tech_stack.tech_stack_id.title }}"
              class="requirements--contents__content-tech-icon-img"
            >
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="requirements--contents__articles">
      <h3 class="requirements--contents__title">関連記事</h3>
      <div class="requirements--contents__content">
        <h4>フロントエンド</h4>
        <div class="requirements--contents__article-list">
        {% for article in req_detail.articles_set.all %}
          {% if article.categories == 'frontend' %}
          <a href="{{article.url}}" class="requirements--contents__article" id="ogp-{{ article.id }}" target="_blank">
            <div class="requirements--contents__article-text">{{article.title}}</div>
          </a>
          {% endif %}
        {% endfor %}
        </div>
      </div>
      <div class="requirements--contents__content">
        <h4>バックエンド</h4>
        <div class="requirements--contents__article-list">
        {% for article in req_detail.articles_set.all %}
          {% if article.categories == 'backend' %}
          <a href="{{article.url}}" class="requirements--contents__article" id="ogp-{{ article.id }}" target="_blank">
            <div class="requirements--contents__article-text">{{article.title}}</div>
          </a>
          {% endif %}
        {% endfor %}
        </div>
      </div>
      <div class="requirements--contents__content">
        <h4>インフラ</h4>
        <div class="requirements--contents__article-list">
        {% for article in req_detail.articles_set.all %}
          {% if article.categories == 'infra' %}
          <a href="{{article.url}}" class="requirements--contents__article" id="ogp-{{ article.id }}" target="_blank">
            <div class="requirements--contents__article-text">{{article.title}}</div>
          </a>
          {% endif %}
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>