app/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls")),
    path('requirements/',include("requirements.urls")),
    path('inquiry/', include('inquiry.urls')),
    path('portral/',include("portral.urls")),
    path("", lambda request: redirect("accounts:login")),
    path('answers/', include('answers.urls')),
]

app/requirements/urls.py
from django.urls import path
from . import views
app_name = "requirements"
urlpatterns=[
    path("form/",views.form,name="form"),
    path("list/",views.list,name="list"),
    path("list/<int:id>",views.list_detail,name="list_detail"),
]

app/requirements/models.py
from django.db import models
import uuid
from pathlib import Path
from accounts.models import Users

class Requirements(models.Model):
    user_id=models.ForeignKey(Users,
                           on_delete=models.CASCADE,
                           db_column='user_id',
                           to_field='id',verbose_name='ユーザーID')
    title=models.CharField(max_length=255,null=False,verbose_name='タイトル')
    content=models.TextField(null=False,verbose_name='内容')
    difficulty = models.CharField(max_length=10, choices=[
    ('low', '初級'),
    ('mid', '中級'),
    ('high', '上級'),
    ], default='mid',verbose_name='難易度')
    participants=models.IntegerField(default=0,verbose_name='参加人数')
    #techは削除
    team=models.CharField(null=False,max_length=255,verbose_name='チーム名')
    is_public=models.BooleanField(default=False,verbose_name='公表、非公表')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

class Articles(models.Model):
    requirement_id=models.ForeignKey(Requirements,
                                     on_delete=models.CASCADE,
                                     db_column='requirements_id',
                                     to_field='id')
    category_choices=[
        ('frontend','フロントエンド'),
        ('backend','バックエンド'),
        ('infra','インフラ')
    ]
    categories=models.CharField(max_length=20,
                                choices=category_choices,
                                null=False,
                                verbose_name='カテゴリー')
    title=models.CharField(max_length=255,null=False,verbose_name='タイトル')
    url=models.TextField(null=False,verbose_name='url')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

class tech_stacks(models.Model):
    title=models.CharField(max_length=63,null=False,verbose_name='技術名')
    img_url=models.URLField(null=False,verbose_name='画像のurl')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

class requirements_tech_stacks(models.Model):
    requirement_id=models.ForeignKey(Requirements,
                                     on_delete=models.CASCADE,
                                     db_column='requirements_id',
                                     to_field='id')
    tech_stack_id=models.ForeignKey(tech_stacks,
                                     on_delete=models.CASCADE,
                                     db_column='tech_stack_id',
                                     to_field='id')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="作成日時")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新日時")

app/requirements/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from django.contrib import messages
import re
from .models import Requirements,Articles,tech_stacks,requirements_tech_stacks
from accounts.models import Users
from django.contrib.auth.decorators import login_required

class RequirementFormView(View):
    def get(self,request):
        return render(request,"requirements/form.html")

    def post(self,request):
        user_id=request.session.get('id')
        user=Users.objects.get(id=user_id)

        title=request.POST.get("title")
        content=request.POST.get("content")
        difficulty=request.POST.get("difficulty")
        participants=request.POST.get("participants")
        techs=request.POST.getlist("techs") #複数の使用技術を受け取る
        team=request.POST.get("team")
        save_type=request.POST.get("save_type")
        if save_type=="private":
            is_public=True
        else:
            is_public=False
        
        
        requirement=Requirements.objects.create(
            user_id=user,
            title=title,
            content=content,
            difficulty=difficulty,
            team=team,
            participants=participants,
            is_public=is_public
        )

        tech_objects = tech_stacks.objects.filter(title__in=techs)
        for tech in tech_objects:
          requirements_tech_stacks.objects.create(
          requirement_id=requirement,  # 紐付けたい Requirement
           tech_stack_id=tech           # 取得した TechStack オブジェクト
        )        

        categories={
            'frontend':('frontend-title','frontend-url'),
            'backend':('backend-title','backend-url'),  
            'infra':('infra-title','infra-url')}
        for category,(title_list,url_list) in categories.items():
            titles=request.POST.getlist(title_list)
            urls=request.POST.getlist(url_list)
            for title,url in zip(titles,urls):
                if title and url:
                    Articles.objects.create(
                        requirement_id=requirement,
                        categories=category,
                        title=title,
                        url=url,
                    )
        return redirect('requirements:form')

class RequirementsListView(View):
    def get(self,request):
        requirments=Requirements.objects.prefetch_related('articles_set',
                                                          'requirements_tech_stacks_set__tech_stack_id').all()
        return render(request,"requirements/list_practice.html",{'requirements':requirments})

class RequirementListDetail(View):
    def get(self,request,id):
        req_detail=Requirements.objects.prefetch_related('articles_set',
                                                        'requirements_tech_stacks_set__tech_stack_id').get(id=id)
        #応募者の表示
        users = Users.objects.filter(
                        base_skills__base_skills_requirements__requirement_id=id).distinct()
        return render(request,"requirements/detail_practice.html",{'req_detail':req_detail,'users':users})
        
form=RequirementFormView.as_view()
list=RequirementsListView.as_view()
list_detail=RequirementListDetail.as_view() 

app/templates/requirements/detail.html
{% extends 'base/base_user.html' %}
{% block head %}
  <title>要件詳細</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/components/header.css' %}" />
  <link rel="stylesheet" href="{% static 'css/components/requirements_sheet.css' %}" />
  <link rel="stylesheet" href="{% static 'css/components/three_levels.css' %}" />
  <link rel="stylesheet" href="{% static 'css/requirements/detail.css' %}" />
{% endblock %}
{% block body %}
  {% include 'components/header.html' %}
  <div class="body--wrap">
    {% include 'components/requirements_sheet.html' %}
    <form class="requirements-form" method="post">
        {% csrf_token %}
      <h3 class="requirements-form-title">応募フォーム</h3>
      <div>
        <h4 class="requirements-form--sub-title">希望ポジション</h4>
        <div class="three-levels--button">
          <input type="radio" name="position" value="frontend" id="front" /><label for="front" class="three-levels--button__text three-levels--button__green">フロント</label>
          <input type="radio" name="position" value="backend" id="back" /><label for="back" class="three-levels--button__text three-levels--button__blue">バック</label>
          <input type="radio" name="position" value="infra" id="infra" /><label for="infra" class="three-levels--button__text three-levels--button__red">インフラ</label>
        </div>
      </div>
      <div>
        <h4 class="requirements-form--sub-title">現在のステップ数</h4>
        <input type="number" name="step" min="0", max="500" placeholder="例：150" class="requirements-form--input-text requirements-form--input-number" />
      </div>
      <div class="requirements-form--column">
        <h4 class="requirements-form--sub-title">週のコミット可能時間</h4>
        <div class="requirements-form--text"><input type="radio" name="commit_time" value="10h" id="10h" /><label for="10h">10h</label></div>
        <div class="requirements-form--text"><input type="radio" name="commit_time" value="15h" id="15h" /><label for="15h">15h</label></div>
        <div class="requirements-form--text"><input type="radio" name="commit_time" value="20h" id="20h" /><label for="20h">20h</label></div>
        <div class="requirements-form--text"><input type="radio" name="commit_time" value="20h~" id="20h~" /><label for="20h~">20h~</label></div>
      </div>
      <div>
        <h4 class="requirements-form--sub-title">稼働想定日時</h4>
        <input type="text" name="work_time" placeholder="例：平日20時以降" class="requirements-form--input-text"  />
      </div>
      <div class="requirements-form--column">
        <h4 class="requirements-form--sub-title">Git・GitHubについて</h4>
        <div class="requirements-form--text"><input type="radio" name="git_skill" value="1" id="poor" /><label for="poor">Git及びGitHubがわからない</label></div>
        <div class="requirements-form--text"><input type="radio" name="git_skill" value="2" id="good" /><label for="good">Git及びGitHubは使ったことはあるが、言語化は厳しい</label></div>
        <div class="requirements-form--text"><input type="radio" name="git_skill" value="3" id="great" /><label for="great">Git及びGitHubはだいたいわかっていて、人にも説明できる。</label></div>
      </div>
      <div class="requirements-form--column">
        <h4 class="requirements-form--sub-title">開発経験について</h4>
        <div class="requirements-form--text"><input type="radio" name="development_experience" value="1" id="beginner" /><label for="beginner">開発経験なし</label></div>
        <div class="requirements-form--text"><input type="radio" name="development_experience" value="2" id="elementary" /><label for="elementary">開発経験あり（ハッカソン入門コースのみ・実務未経験）</label></div>
        <div class="requirements-form--text"><input type="radio" name="development_experience" value="3" id="intermediate" /><label for="intermediate">実務経験1年未満</label></div>
        <div class="requirements-form--text"><input type="radio" name="development_experience" value="4" id="advanced" /><label for="advanced">実務経験1年以上</label></div>
      </div>
      <input type="submit" class="submit-button" value="提出" />
    </form>
  </div>
  <script src="{% static 'js/get_ogp.js' %}"></script>
  <script>getAnkerByOgp();</script>
{% endblock %}

app/templates/requirements/form.html
<!DOCTYPE html>
<html lang="ja">
    
    <head>
        <meta charset="utf-8">
        <title>要件定義作成</title>

    </head>
    <body>
     

      {% if messages %}
        <ul>
         {% for message in messages %} 
           <li>{{ message }}</li>
         {% endfor %}
        </ul>
      {% endif %}
         
      <form class="requirements_form" method="post">
        {% csrf_token %}
        <div>
          <label for="title">タイトル</label>
          <input
            type="text"
            placeholder="タイトル"
            name="title"
            id="title"  
            maxlength="255"
          />
        </div>
        <div>
          <label for="content">要件</label>
          <textarea
            placeholder="内容を入力しください"
            name="content"
            id="content"
          ></textarea>
        </div>

        <div>
          <label for="content">難易度</label>
          <select name="difficulty" id="">
            <option value="low">初級</option>
            <option value="mid">中級</option>
            <option value="high">上級</option>
          </select>
        </div>

        <div>
          <label for="participants">参加人数</label>
          <input
            type="text"
            placeholder="参加人数を入力してください"
            name="participants"
            id="participants"
          />
        </div>

        <div>
          <label for="team">チーム名</label>
          <input
            type="text"
            placeholder="チーム名を入力してください"
            name="team"
            id="team"
          />
        </div>


        <!--フロントエンド記事-->
        <h2>記事</h2>
        <label>フロントエンド</label>
        <div>
          <label for="frontend-title">タイトル</label>
          <input
           type="text"
           name="frontend-title"
           id="frontend-title"
           placeholder="タイトルを入力してください">
        </div>
        <div>
          <label for="frontend-url">URL</label>
          <input
           type="url"
           id="frontend-url"
           name="frontend-url"
           placeholder="urlを入力してください">
        </div>

        <div>
          <label for="frontend-title">タイトル</label>
          <input
           type="text"
           name="frontend-title"
           id="frontend-title"
           placeholder="タイトルを入力してください">
        </div>
        <div>
          <label for="frontend-url">URL</label>
          <input
           type="url"
           id="frontend-url"
           name="frontend-url"
           placeholder="urlを入力してください">
        </div>

        <!--バックエンド記事-->
        <label>バックエンド</label>
        <div>
          <label for="backend-title">タイトル</label>
          <input
           type="text"
           name="backend-title"
           id="backend-title"
           placeholder="タイトルを入力してください">
        </div>
        <div>
          <label for="backend-url">URL</label>
          <input
           type="url"
           id="backend-url"
           name="backend-url"
           placeholder="urlを入力してください">
        </div>

        <div>
          <label for="backend-title">タイトル</label>
          <input
           type="text"
           name="backend-title"
           id="backend-title"
           placeholder="タイトルを入力してください">
        </div>
        <div>
          <label for="backend-url">URL</label>
          <input
           type="url"
           id="backend-url"
           name="backend-url"
           placeholder="urlを入力してください">
        </div>

        <!--インフラ記事-->
        <label>インフラ</label>
        <div>
          <label for="infra-title">タイトル</label>
          <input
           type="text"
           name="infra-title"
           id="infra-title"
           placeholder="タイトルを入力してください">
        </div>
        <div>
          <label for="infra-url">URL</label>
          <input
           type="url"
           id="infra-url"
           name="infra-url"
           placeholder="urlを入力してください">
        </div>

        <div>
          <label for="infra-title">タイトル</label>
          <input
           type="text"
           name="infra-title"
           id="infra-title"
           placeholder="タイトルを入力してください">
        </div>
        <div>
          <label for="infra-url">URL</label>
          <input
           type="url"
           id="infra-url"
           name="infra-url"
           placeholder="urlを入力してください">
        </div>



        <h2>使用技術</h2>
        <!-- 使用技術のボタン -->
        <label>
            <input type="checkbox" name="techs" value="HTML">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/html-5_5968267.png" width="40px">
            HTML
        </label>

        <label>
            <input type="checkbox" name="techs" value="CSS">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/css-3_5968242.png" width="40px">
            CSS
        </label>

        <label>
            <input type="checkbox" name="techs" value="JavaScript">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/js_5968292.png" width="40px">
            JavaScript
        </label><br>

        <label>
            <input type="checkbox" name="techs" value="Python">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/python-logo-only.png" width="40px">
            Python
        </label>

        <label>
            <input type="checkbox" name="techs" value="Flask">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/icons8-%E3%83%95%E3%83%A9%E3%82%B9%E3%82%B3-100.png" width="40px">
            Flask
        </label>

        <label>
            <input type="checkbox" name="techs" value="Django">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/django-logo-negative.png" width="40px">
            Django
        </label>

        <label>
            <input type="checkbox" name="techs" value="Java">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/icons8-java-coffee-cup%E3%81%AE%E3%83%AD%E3%82%B3%E3%82%99-96.png" width="40px">
            Java
        </label>

        <label>
            <input type="checkbox" name="techs" value="Quarkus">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/quarkus_icon_512px_default.png" width="40px">
            Quarkus
        </label>

        <label>
            <input type="checkbox" name="techs" value="MySQL">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/logo-mysql-170x115.png" width="40px">
            MySQL
        </label>

        <label>
            <input type="checkbox" name="techs" value="Postgre">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/elephant.png" width="40px">
            Postgre
        </label><br>

        <label>
            <input type="checkbox" name="techs" value="Docker">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/docker-mark-blue.png" width="40px">
            Docker
        </label>

        <label>
            <input type="checkbox" name="techs" value="AWS">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/icons8-aws-96.png" width="40px">
            AWS
        </label>

        <label>
            <input type="checkbox" name="techs" value="Teraform">
            <img src="https://hackathon-dev-image-dteam.s3.ap-northeast-1.amazonaws.com/icons8-%E3%83%86%E3%83%A9%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0-96.png" width="40px">
            Teraform
        </label>


        

         <div>
            <button type="submit" name="save_type" value="public">公開して保存</button>
            <button type="submit" name="save_type" value="private">非公開で保存</button>
         </div>
      </form>

      <a href="{% url 'accounts:login' %}">
        <button type="button">ログイン画面に戻る</button>
      </a>

    </body>
   



</html>

app/templates/requirements/index.html
{% extends 'base/base_user.html' %}
{% block head %}
  <title>要件一覧</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/components/header.css' %}" />
  <link rel="stylesheet" href="{% static 'css/requirements/index.css' %}" />
{% endblock %}
{% block body %}
  {% include 'components/header.html' %}
  <div class="body--wrap">
    <ul class="requirements-lists">
      {% for requirement in requirements %}
      <a href='{{requirement.id}}'>
        <li class="requirements-list">
          <div class="requirements-list--left">
            <div class="requirements-list--left__title">{{ requirement.title }}</div>
            <div class="requirements-list--left__stacks">
              <div class="requirements-list--left__stacks-title">技 術</div>
              <div class="requirements-list--left__stacks-icons">
              {% for tech_stack in requirement.requirements_tech_stacks_set.all %}
                <div class="requirements-list--left__stacks-icon">
                  <img
                    src="{{ tech_stack.tech_stack_id.img_url }}"
                    alt="{{ tech_stack.tech_stack_id.title }}"
                    class="requirements-list--left__stacks-icon-img"
                  >
                </div>
              {% endfor %}
              </div>
            </div>
          </div>
          <div class="requirements-list--right">
            <div class="requirements-list--right__contents">
              <div class="requirements-list--right__contents-title">難易度</div>
              <div class="requirements-list--right__contents-border"></div>
              <div class="requirements-list--right__contents-main">{{ requirement.get_difficulty_display }}</div>
            </div>
            <div class="requirements-list--right__contents">
              <div class="requirements-list--right__contents-title">応募数</div>
              <div class="requirements-list--right__contents-border"></div>
              <div class="requirements-list--right__contents-main">{{ requirement.participants }}人</div>
            </div>
          </div>
        </li>
      </a>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

app/templates/requirements/success.html
<h1>成功</h1>